services:
  strapi:
    build: ./strapi
    env_file:
      - ./strapi/.env
    ports:
      - '1337:1337'
    volumes:
      - strapi-app:/srv/app
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:1337/"]
      interval: 10s
      timeout: 20s
      retries: 10

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=strapi
      - POSTGRES_USER=strapi
      - POSTGRES_PASSWORD=changeme
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - strapi-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 20s
      retries: 10

volumes:
  strapi-app:
  strapi-postgres:
