/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        'cloudy-day-white': 'var(--cloudy-day-white)',
        'overcast': 'var(--overcast)',
        'sand-dune-brown': 'var(--sand-dune-brown)',
        'craters-moon': 'var(--craters-moon)',
        'desert-cliff-brown': 'var(--desert-cliff-brown)',
        'clay-pidgeon-orange': 'var(--clay-pidgeon-orange)',
        'gunclub-orange': 'var(--gunclub-orange)',
        'wildeye-susan-yellow': 'var(--wildeye-susan-yellow)',
        'idaho-sky-blue': 'var(--idaho-sky-blue)',
        'snakeriver-blue': 'var(--snakeriver-blue)',
        'owyhee-green': 'var(--owyhee-green)',
        'boise-yard-green': 'var(--boise-yard-green)',
        'scoring-bench-red': 'var(--scoring-bench-red)',
        'kent-slate-gray': 'var(--kent-slate-gray)',
        'ed-charcoal': 'var(--ed-charcoal)',
        'pigeon-clay-gray': 'var(--pigeon-clay-gray)',
        'chester-white': 'var(--chester-white)',
        'don-gray': 'var(--don-gray)',
        'leonard-yellow': 'var(--leonard-yellow)',
        'lahoma-orange': 'var(--lahoma-orange)',
        'jerry-orange': 'var(--jerry-orange)',
        'abe-red': 'var(--abe-red)',
        'club-house-roof-blue': 'var(--club-house-roof-blue)',
        'club-house-walk-gray': 'var(--club-house-walk-gray)',
        'club-house-lawn-green': 'var(--club-house-lawn-green)',
        'bg-primary': 'var(--bg-primary)',
        'bg-secondary': 'var(--bg-secondary)',
        'bg-tertiary': 'var(--bg-tertiary)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'accent-primary': 'var(--accent-primary)',
        'accent-secondary': 'var(--accent-secondary)',
        'accent-tertiary': 'var(--accent-tertiary)',
        'card': 'var(--card)',
        'card-foreground': 'var(--card-foreground)',
        'muted': 'var(--muted)',
        'muted-foreground': 'var(--muted-foreground)',
        'brand-blue': 'var(--brand-blue)',
        'brand-green': 'var(--brand-green)',
        'brand-red': 'var(--brand-red-action)',
        'brand-red-action': 'var(--brand-red-action)',
      },
      fontFamily: {
        heading: ['var(--font-heading)', 'sans-serif'],
        body: ['var(--font-body)', 'sans-serif'],
      },
      transitionDuration: {
        'fast': '150ms',
        'smooth': '300ms',
      },
      transitionTimingFunction: {
        'fast': 'cubic-bezier(0.215, 0.61, 0.355, 1)',
        'smooth': 'cubic-bezier(0.215, 0.61, 0.355, 1)',
      },
      boxShadow: {
        'sm': '0 2px 4px -1px rgba(50,50,93,.25)',
        'md': '0 4px 8px -2px rgba(50,50,93,.25)',
        'lg': '0 8px 16px -4px rgba(50,50,93,.25)',
      },
      animation: {
        'shimmer': 'shimmer 2s ease-in-out infinite',
      },
      keyframes: {
        shimmer: {
          '0%': { transform: 'translateX(-100%)' },
          '50%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
      },
    },
  },
  plugins: [],
};
